id: I0379C3DF
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:05:19.036315
last_modified: 2023-02-08 15:05:19.036511
source_metadata:
  title: Gaganagañjaparipṛcchā
  language: sa
bases:
  9EA2:
    base_file: 9EA2.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
